# Generated by Django 4.1.7 on 2023-04-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('level', models.CharField(blank=True, max_length=16, null=True)),
                ('ionization', models.CharField(blank=True, max_length=16, null=True)),
                ('polarity', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.spectrummeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.CharField(blank=True, max_length=32, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.spectrummeasurement')),
            ],
        ),
    ]
