# Generated by Django 4.1.7 on 2023-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_spectrumfield_key_alter_spectrumfield_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrummeasurement',
            name='ionization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spectrummeasurement',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spectrummeasurement',
            name='polarity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spectrummeasurement',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
