# Generated by Django 4.1.7 on 2023-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_spectrummeasurement_ionization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumpeak',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
