# Generated by Django 4.1.7 on 2023-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_spectrumpeak_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumpeak',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
